src/HASS.Agent.Staging/HASS.Agent.Shared/HomeAssistant/Commands/InternalCommands/SetVolumeCommand.cs

This PR fixes bug reported by @Boeboey in the official repository https://github.com/LAB02-Research/HASS.Agent/issues/363.
Issue has been caused by "_volume" variable being static meaning that the last instance configured by HASS.Agent would set the volume level for all commands.

Fix: SetVolumeCommand supporting only one instance

---

src/HASS.Agent.Staging/HASS.Agent/Functions/CompatHelper.cs

This PR:
- fixes issue where exception is thrown if check for HA version is made, whilst there is no actual connection to HA
- adds additional checks to the CompatHelper to make sure that in worst case scenario "false" is returned instead of exception
Cases for the edge case:
- user tries to add sensor/command when HASS.Agent was never fully configured
- user tries to add sensor/command before HASS.Agent makes connection to HA (+-ten-ish seconds after HASS.Agent starts)
- user tries to add sensor/command after connection between HASS.Agent and HA is broken
Should remediate part of the issue reported via https://github.com/amadeo-alex/HASS.Agent/issues/10

Fix: CompatHelper throwing exception when there is no connection to HA

---

src/HASS.Agent.Staging/HASS.Agent/Forms/Commands/CommandsMod.cs
src/HASS.Agent.Staging/HASS.Agent/Forms/Main.cs
src/HASS.Agent.Staging/HASS.Agent/Forms/Sensors/SensorsMod.cs
src/HASS.Agent.Staging/HASS.Agent/HASS.Agent.csproj
src/HASS.Agent.Staging/HASS.Agent/HomeAssistant/Commands/CustomCommands/SwitchDesktopCommand.cs
src/HASS.Agent.Staging/HASS.Agent/HomeAssistant/Sensors/GeneralSensors/SingleValue/ActiveDesktopSensor.cs
src/HASS.Agent.Staging/HASS.Agent/Managers/VirtualDesktopManager.cs
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.Designer.cs
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.de.resx
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.en.resx
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.es.resx
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.fr.resx
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.nl.resx
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.pl.resx
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.pt-br.resx
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.resx
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.ru.resx
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.sl.resx
src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.tr.resx

This PR:
- changes VirtualDesktop library to https://github.com/Slion/VirtualDesktop (maintained fork of the original one)
- adds backend checks for library initialisation - library is wrapped into a manager class 
- adds checks for user trying to add virtual desktop sensor/command which prevent them to be added
- adds checks for the specific functions used by the virtual desktop sensor/command in case of manual configuration in the json files
Should remediate second issue reported in https://github.com/amadeo-alex/HASS.Agent/issues/10
Error presented to the user when trying to configure sensor/command in unsupported setup:
Error printed to the logs when unsupported setup is detected:

Fix: Virtual Desktop management availability handling

---

src/HASS.Agent.Staging/HASS.Agent.Satellite.Service/MQTT/MqttManager.cs
src/HASS.Agent.Staging/HASS.Agent.Shared/Mqtt/IMqttManager.cs
src/HASS.Agent.Staging/HASS.Agent/Forms/Main.cs
src/HASS.Agent.Staging/HASS.Agent/MQTT/MqttManager.cs
src/HASS.Agent.Staging/HASS.Agent/Program.cs

This PR:
- fixes HASS.Agent being always added to startup on launch
- fixes notification being dismissed when
- it was activated when HASS.Agent was offline (notification was parsed while there was no connection to MQTT broker)
As a side effect of the second fix, MQTT managers now present "IsReady()" function which returns true when they are ready to send/process messages.

Fix: duplicate startup entry & notification activation handling while HASS.Agnet is offline

---

src/HASS.Agent.Staging/HASS.Agent.Satellite.Service/Worker.cs
src/HASS.Agent.Staging/HASS.Agent.Shared/HomeAssistant/Sensors/GeneralSensors/SingleValue/GpuLoadSensor.cs
src/HASS.Agent.Staging/HASS.Agent.Shared/HomeAssistant/Sensors/GeneralSensors/SingleValue/GpuTemperatureSensor.cs
src/HASS.Agent.Staging/HASS.Agent.Shared/Managers/HardwareManager.cs
src/HASS.Agent.Staging/HASS.Agent/Forms/Main.cs

This PR:
- fixes issue where hardware sensors (GPU load and temperature) would silently crash the application due to the memory violation.
- adds additional check for Intel GPU (AMD->NVIDIA->Intel)
Should remediate https://github.com/amadeo-alex/HASS.Agent/issues/14
The root cause of the issue was "closing of computer" class from LibreHardwareMonitor after obtaining the GPU object.
This has been remediated by introducing a HardwareManager class.

Fix: hardware sensors crashing application

---

.github/workflows/build.yml

GitHub Action to compile the solution on GitHub and upload build artifacts (Agent, Satellite, and Shared) to the current run that can be downloaded. ~~It _does not_ draft releases as there are several ways to go about that.~~
Runs on:
- On demand via GitHub Actions
Commented out a few sections around code signing. See the following screenshot for results of this Action.

Build Project and Upload results to Github

---

.github/workflows/build.yml
README.md
src/HASS.Agent.Installer/InstallerScript.iss
src/HASS.Agent/HASS.Agent/Compatibility/MigrateCompatibilityTask.cs

This PR
- fixes null reference exception if source (original HASS.Agent) registry keys do not exist
- makes the migration task deselected by default

Fix: null referece within migration task

---

src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
src/HASS.Agent/HASS.Agent/HASS.Agent.csproj

This PR adds project property that makes the build system skip github commit hash as a postfix.

Fix: product version including github hash

---

src/HASS.Agent.Installer/InstallerScript.iss
src/HASS.Agent/HASS.Agent/Managers/UpdateManager.cs

This PR contains quick fix for UpdateManager exception when product version is malformed.

Fix: update manager crash on malformed version

---

src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
src/HASS.Agent/HASS.Agent/HASS.Agent.csproj

This PR attempts to fix HASS.Agent crash when virtual desktops are switched.
Probable root cause was bug in the management library HASS.Agent uses, this PR bumps the dependency version of this library to newest version.

Fix: crash on virtual destkop switch

---

src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/PowershellSensor.cs
src/HASS.Agent/HASS.Agent.Shared/Models/HomeAssistant/AbstractSingleValueSensor.cs

This PR fixes issue where the "LastUpdated" value is not updated if sensor value is same as previously.
Thanks to @Shupershuff for reporting the issue :)
Due to this issue sensor's "GetState" would be called every second or often. For most of the sensors it wasn't an issue but in some cases where custom code (for example PowerShell sensor) is used, this may result in the code/script being run "constantly" without respect for the "Update every" sensor configuration.
Before:
After:

Fix: sensor being updated constantly when value doesn't change

---

src/HASS.Agent/HASS.Agent.Shared/Managers/PowershellManager.cs

This PR fixes how action arguments are passed on to the PowershellCommand.
Previously whole action string was passed as a one argument, this prevented parameter binding - after the changes the action string itself defines how the parameter/s will be handled.
Thanks to @Shupershuff for reporting :)
Test script configured with PowershellCommand:
```
param ([string]$test1,[string]$test2,[string]$test3)
$WorkingDirectory = ((Get-ChildItem -Path $PSScriptRoot)[0].fullname).substring(0,((Get-ChildItem -Path $PSScriptRoot)[0].fullname).lastindexof('\')) #Set #Current Directory path.
$wshell = New-Object -ComObject Wscript.Shell
$wshell.Popup("runs " + $PsBoundParameters.Values + "  :::::  " + $args,1,"Done",0x1)
$PsBoundParameters.Values >> $WorkingDirectory\sumlogs.txt
$DateTime = …
```

Fix: Powershell command argument binding

---

src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/GeneralSensors/SingleValue/ActiveWindowSensor.cs

This PR fixes window title sensor encoding issue reported by Evostance.
Before:
After:
In addition, changes were made to ensure the window title length sent to HA will not exceed 255 characters - max HA payload/state length.

Fix: active window title encoding

---

src/HASS.Agent/HASS.Agent.Satellite.Service/Commands/CommandsManager.cs
src/HASS.Agent/HASS.Agent.Satellite.Service/Sensors/SensorsManager.cs
src/HASS.Agent/HASS.Agent/Commands/CommandsManager.cs
src/HASS.Agent/HASS.Agent/Sensors/SensorsManager.cs

This PR changes the MQTT behaviour to limit the times where MQTT discovery payload for entities is sent to the broker.
Huge thanks for @Anto79-ops for reporting this on Discord :)
After the changes the discovery messages are sent:
- after HASS.Agent starts
- after configuration change

Fix: constant MQTT discovery payload publish

---

src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.Designer.cs
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.de.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.en.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.es.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.fr.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.nl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pt-br.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.ru.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.sl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.tr.resx

This PR changes the microphone process sensor description to better reflect its functionality (https://github.com/hass-agent/HASS.Agent/issues/49):
```
Provides the number of the processes that currently use the microphone - additionally provides name of the processes in the sensor's attributes.
Note: if used in the satellite service, it won't detect userspace applications.
```

Fix: microphone process sensor description

---

src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
src/HASS.Agent/HASS.Agent/HASS.Agent.csproj

This PR bumps all possible dependencies to newest versions.
The Windows AppSDK has been updated to the newest 1.4.X instead to 1.5.X due to bug/incompatibility with WebView.

Development: 2.1.0-beta1 dependency bump

---

src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.Designer.cs
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.de.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.en.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.es.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.fr.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.nl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pt-br.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.ru.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.sl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.tr.resx

This PR adds additional note reminding users about maximum payload length that Home Assistant supports.
```
Returns the result of the provided Powershell command or script.
Note: please keep in mind that Home Assistant accepts payload up to 255 characters.
Converts the outcome to text.
```

Fix: PowerShell sensor character limit note

---

src/HASS.Agent/HASS.Agent/Forms/Main.cs

This simple PR fixes the issue where configuration subwindows would stay open (in some cases in broken state) after the main windows was closed by the user.
Thanks to @KohGeek for reporting :)

Fix: close all subwindows when main one is closed

---

src/HASS.Agent/HASS.Agent/MQTT/MqttManager.cs

This PR adds additional cleanup for device and media player MQTT discovery messages than can cause HASS.Agent not to be rediscovered after changing device name - https://github.com/hass-agent/HASS.Agent/issues/68
Current proper way to rename HASS.Agent device:
- rename device in HASS.Agent
- remove device from HA integration
- restart HA
After doing so, "new device name" should be discovered by HA.
Without this fix, discovery configuration message with previous name wouldn't be removed which could cause the "new device name" not to be discovered at all, even after removing old one.
Thanks for @Mystically11 for reporting this!

Fix: device rename MQTT messages cleanup

---

src/HASS.Agent/HASS.Agent/Functions/HelperFunctions.cs

This PR adds additional check for the german input language being installed on system.
Should remediate cases where mixed language systems (English UI with German keyboard layout) do not present the notification regarding HotKey collision - https://github.com/hass-agent/HASS.Agent/issues/62

Fix: added additional check for mixed german keyboard layouts

---

src/HASS.Agent/HASS.Agent/Forms/Commands/CommandsMod.cs

This PR fixed commands friendly name not being properly saved when creating/editing sensors - entity name was used instead.

Fix: command friendly name not saving

---

src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/GeneralSensors/MultiValue/WindowsUpdatesSensors.cs

This PR fixes issue reported by @zanix - https://github.com/hass-agent/HASS.Agent/issues/89 - where windows updates sensors would use entity name as the unique UI.
This resulted in Home Assistant rejecting the sensors if more than one device in one MQTT network reported them.

Fix: windows updates sensor missing uniqueid

---

src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/GeneralSensors/SingleValue/ActiveWindowSensor.cs

This PR adds missing parameter enabling attributes for the active window sensor.

Fix: added lost useAttributes parameter

---

src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Commands/MultipleKeysCommand.cs
src/HASS.Agent/HASS.Agent/Commands/CommandsManager.cs
src/HASS.Agent/HASS.Agent/Forms/Commands/CommandsMod.cs
src/HASS.Agent/HASS.Agent/Functions/HelperFunctions.cs

This PR adds functionality requested via https://github.com/hass-agent/HASS.Agent/issues/97 - action parameter support for "MultipleKeys" command.
As of now, the "Key" command has been left unchanged.
Example:
```
service: mqtt.publish
data:
qos: 0
retain: false
topic: homeassistant/button/AMADEO-PC/multiplekeys/action
payload: "[Test][ ][1][2][3]"
```

Feature: "MultipleKeys" command support for action parameter

---

src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
src/HASS.Agent/HASS.Agent.Shared/Managers/Audio/AudioManager.cs
src/HASS.Agent/HASS.Agent.Shared/Managers/Audio/Internal/CPolicyConfigVistaClient.cs
src/HASS.Agent/HASS.Agent.Shared/Managers/Audio/Internal/DeviceChangeEventArgs.cs
src/HASS.Agent/HASS.Agent.Shared/Managers/Audio/Internal/IPolicyConfigVista.cs
src/HASS.Agent/HASS.Agent.Shared/Managers/Audio/Internal/InternalAudioDevice.cs
src/HASS.Agent/HASS.Agent.Shared/Managers/Audio/Internal/InternalAudioSession.cs
src/HASS.Agent/HASS.Agent.Shared/Managers/Audio/Internal/InternalAudioSessionManager.cs
src/HASS.Agent/HASS.Agent.Shared/Managers/Audio/Internal/MMNotificationClient.cs
src/HASS.Agent/HASS.Agent/Managers/SystemStateManager.cs
src/HASS.Agent/HASS.Agent/Media/MediaManager.cs

This PR:
- changes the audio library to NAudio
- fixed issue with media playback using deprecated method that occasionally resulted in access memory violation
- adds additional logic to handle audio management after system has been put to sleep
Related to https://github.com/hass-agent/HASS.Agent/issues/64

Fix: audio library/sleep management/playback

---

src/HASS.Agent/HASS.Agent.Shared/Managers/Audio/AudioManager.cs
src/HASS.Agent/HASS.Agent/Media/MediaManager.cs

This PR fixes:
- audio devices returned from AudioManager not having "Mute" attribute assigned properly
- media player not reporting mute status (reported via https://github.com/hass-agent/HASS.Agent/issues/100)

Fix: device & media player mute parameter

---

src/HASS.Agent/HASS.Agent.Satellite.Service/Extensions/RpcExtensions.cs
src/HASS.Agent/HASS.Agent.Satellite.Service/RPC/Protos/hassagentsatellite.proto
src/HASS.Agent/HASS.Agent/Extensions/RpcExtensions.cs
src/HASS.Agent/HASS.Agent/Service/Protos/hassagentsatellite.proto

This PR fixes advanced settings not being properly saved for satellite sensors.
Thanks to @spikeygg for reporting.
Related to following request: https://github.com/hass-agent/HASS.Agent/issues/66

Fix: advanced settings not being saved for satellite sensors

---

src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/WmiQuerySensor.cs
src/HASS.Agent/HASS.Agent.Shared/Models/HomeAssistant/AbstractSingleValueSensor.cs

This PR fixes sensor's base class not properly parsing/saving advanced settings.

Fix: sensor's base class not saving advanced properties

---

src/HASS.Agent.Installer/InstallerScript-Service.iss

This PR adds "ignoreversion" to the service installer.
Will allow for easier development build testing.

Fix: added installer ignoreversion paramter

---

src/HASS.Agent.Installer/InstallerScript-Service.iss

This PR fixes satellite installer so it properly respects user's choice of installation path and registers the satellite's executable.
Thanks to mavericknik for reporting on discord and testing!

Fix: satellite service installer not respecting user selected path

---

src/HASS.Agent.Installer/InstallerScript-Service.iss
src/HASS.Agent/HASS.Agent.Satellite.Service/Extensions/RpcExtensions.cs
src/HASS.Agent/HASS.Agent.Satellite.Service/RPC/Protos/hassagentsatellite.proto
src/HASS.Agent/HASS.Agent.Satellite.Service/Settings/StoredSensors.cs
src/HASS.Agent/HASS.Agent/Extensions/RpcExtensions.cs
src/HASS.Agent/HASS.Agent/Service/Protos/hassagentsatellite.proto
src/HASS.Agent/HASS.Agent/Settings/StoredSensors.cs

This PR fixes satellite sensors/commands:
- not saving advanced settings
- not saving round configuration
- not saving "ignore availability" option

Fix: satellite service sensors/commands not being properly saved

---

src/HASS.Agent/HASS.Agent.Shared/Enums/HassAction.cs
src/HASS.Agent/HASS.Agent.Shared/Enums/HassDomain.cs
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.Designer.cs
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.de.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.en.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.es.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.fr.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.nl.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.pl.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.pt-br.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.ru.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.sl.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.tr.resx
src/HASS.Agent/HASS.Agent/Forms/QuickActions/QuickActionsMod.cs
src/HASS.Agent/HASS.Agent/HomeAssistant/HassApiManager.cs
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.Designer.cs
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.de.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.en.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.es.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.fr.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.nl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pt-br.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.ru.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.sl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.tr.resx

This PR adds feature requested via https://github.com/hass-agent/HASS.Agent/issues/118 which allows to press Home Assistant buttons via quick actions.

Feature: quick action button press

---

src/HASS.Agent.Installer/InstallerScript-Service.iss

This PR adds additional logic into the installer that will try to make sure the satellite service is actually stopped before progressing with the install process.

Fix: added additional service stop logic

---

src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/AccelerometerSensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/ActivitySensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/AltimeterSensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/BarometerSensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/CompassSensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/GyrometerSensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/HingeAngleSensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/InclinometerSensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/LightSensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/MagnetometerSensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/OrientationSensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/PedometerSensor.cs
src/HASS.Agent/HASS.Agent/Managers/DeviceSensors/ProximitySensor.cs

This PR adds additional logic to prevent null exceptions when one of the sensors is malfunctioning.
Explanation: one of my devices has a light sensor that causes exception each time then measurement is accessed despite the "sensor" being enumerated properly.

Fix: internal device sensor null checks

---

src/HASS.Agent/HASS.Agent/API/ApiEndpoints.cs
src/HASS.Agent/HASS.Agent/Functions/HelperFunctions.cs
src/HASS.Agent/HASS.Agent/MQTT/MqttManager.cs
src/HASS.Agent/HASS.Agent/Managers/NotificationManager.cs
src/HASS.Agent/HASS.Agent/Media/MediaManager.cs
src/HASS.Agent/HASS.Agent/Models/HomeAssistant/MqttMediaPlayerCommand.cs
src/HASS.Agent/HASS.Agent/Models/HomeAssistant/Notification.cs
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.Designer.cs
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.de.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.en.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.es.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.fr.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.nl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pt-br.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.ru.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.sl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.tr.resx

This PR backports features that were developed as part of "v3 rewrite" project.
The added features were based on the Home Assistant's Android notifications documentation - https://companion.home-assistant.io/docs/notifications/notifications-basic/
Example 1: notification with 3 buttons, one input and tag & group so it can be cleared
```
service: notify.amadeo_pc
data:
title: Fancy title
message: Test message
data:
image: >-
https://smea.uw.edu/wp-content/uploads/sites/11/2017/03/CURRENTSBLOG_Cat_2.jpg
actions:
- action: "yes"
title: "Yes"
- action: "no"
title: "No"
- action: "openuri"
title: "Open URI"
uri: "https://www.cat-lovers-only.com"
inputs:
- id: testId
text: testText
title: testTitle
clickAction: "https://www.home-assistant.io/"
tag: "dogsAreCoolToo"
group: "cuddlyOnesTho"
``` …

Feature: v3 notification features backport

---

src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Commands/InternalCommands/SetVolumeCommand.cs

This PR fixes issues of SetVolumeCommand reported via https://github.com/hass-agent/HASS.Agent/issues/173:
- ignoring payload and using internal volume set by default to -1 is not configured (causing no action to be taken)
- accepting only proper ("50") integers and failing to parse float values ("50.0", "50.5")
After the fix, payload is properly recognised and providing float values causes them to be converted to int by rounding up (i.e. "50.1" and above becomes "51")

Fix: SetVolumeCommand ignoring payload

---

src/HASS.Agent/HASS.Agent/MQTT/MqttManager.cs

This PR adds logic required to handle the media player mute service call with user-provided parameter.
Complementary to: https://github.com/hass-agent/HASS.Agent-Integration/pull/15
Related to: https://github.com/hass-agent/HASS.Agent/issues/100

Fix: added logic to handle mute command parameter

---

src/HASS.Agent/HASS.Agent/Program.cs
src/HASS.Agent/HASS.Agent/app.manifest

This PR fixes HASS.Agent UI looking blurry on devices where scaling is set to values other than 100%
Thanks to @IsaacInsoll for reporting! https://github.com/hass-agent/HASS.Agent/issues/183

Fix: application not displaying properly with scale other than 100%

---

src/HASS.Agent/HASS.Agent/Managers/StorageManager.cs
src/HASS.Agent/HASS.Agent/Media/MediaManager.cs

This PR fixes issue reported via https://github.com/hass-agent/HASS.Agent/issues/208 where the media played via Music Assistant would be delayed or play after MA was closed/restarted.
This was due to HASS.Agent trying to download whole media file while MA tried to serve is as a live real-time stream - more details in the issue itself.
Thanks to @felipecrs and @whc2001 for reporting, providing a lot of information and testing :)

Fix: playing media via Music Assistant

---

src/HASS.Agent.Installer/InstallerScript-Service.iss

This PR fixes issue reported via https://github.com/hass-agent/HASS.Agent/issues/193.
According to good security practices the service exe path (ImagePath) should be enclosed in double quotes.
Thanks to @yakidd for reporting!

Fix: service installer not using double quotes around exe path

---

src/HASS.Agent.Installer/InstallerScript-Service.iss
src/HASS.Agent.Installer/InstallerScript.iss
src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
src/HASS.Agent/HASS.Agent/HASS.Agent.csproj

- Satellite Service exe path is now properly enclosed in double quotes according to good security practices (thanks to @yakidd for reporting) https://github.com/hass-agent/HASS.Agent/pull/221
- Media playback via Music Assistant wasn't working correctly (thanks to @felipecrs and @whc2001 for reporting, providing a lot of information and testing) https://github.com/hass-agent/HASS.Agent/pull/220
- PowershellCommand argument handling where passing arguments containing spaces/quotes would cause the command to fail (thanks @greghesp for reporting) https://github.com/hass-agent/HASS.Agent/pull/204
- Restarting "Windows Management Instrumentation (WMI)" while HASS.Agent is running causes all WMI based sensors to stop functioning (thanks to @jack5mikemotown for reporting) …

Release: 2.1.1-beta3

---

src/HASS.Agent/HASS.Agent/Managers/NotificationManager.cs

This PR fixes a bug where the URI option attached to a button wouldn't open the URI upon clicking on it.

Fix: URI not being properly launched when attached to a button

---

src/HASS.Agent/HASS.Agent.Satellite.Service/Commands/CommandsManager.cs
src/HASS.Agent/HASS.Agent.Satellite.Service/Sensors/SensorsManager.cs
src/HASS.Agent/HASS.Agent/Commands/CommandsManager.cs
src/HASS.Agent/HASS.Agent/Sensors/SensorsManager.cs

This PR fixes bug reported via https://github.com/hass-agent/HASS.Agent/issues/228 where after MQTT connection is restored, the autodiscovery messages are not sent. This causes entities to be unavailable in Home Assistant.

Fix: autodiscvoery messaages were not republished after MQTT connection was recovered

---

src/HASS.Agent/HASS.Agent/Managers/UpdateManager.cs

This PR fixes issue reported by @stavismed via https://github.com/hass-agent/HASS.Agent/issues/234 where despite settings being configured not to show update notification, one would be shown after HASS.Agent is started/restarted.
Thanks for reporting!

Fix: do not show update notification on startup when disabled in settings

---

src/HASS.Agent/HASS.Agent/Forms/Main.cs
src/HASS.Agent/HASS.Agent/Managers/UpdateManager.cs
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.Designer.cs
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.de.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.en.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.es.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.fr.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.nl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pt-br.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.ru.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.sl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.tr.resx

This PR fixes issue reported via https://github.com/hass-agent/HASS.Agent/issues/240 where HASS.Agent would show notification stating "running newest version" even when no internet was available.
Thanks to @patienttruth for reporting!

Fix: update check showing running newest version when no internet is available

---

src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/GeneralSensors/SingleValue/GpuLoadSensor.cs
src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/GeneralSensors/SingleValue/GpuTemperatureSensor.cs

This PR removes dependency on LibreHardwareMonitor.
GPU sensors are affected by this change:
- GPU Load Sensor - logic has been replaced with performance counter
- GPU Temperature Sensor - always returns 0, at this point there is no practical way to get this data. A documentation page is going to be prepared how to create a WMI sensor that receives the data from the standalone version of LibreHardwareMonitor. @DrR0X-glitch let me know please if you could do this.

Fix: WinRing0/LibreHardwareMonitor dependency

---

src/HASS.Agent/HASS.Agent.Shared/Enums/SensorType.cs
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.Designer.cs
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.de.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.en.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.es.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.fr.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.nl.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.pl.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.pt-br.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.ru.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.sl.resx
src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.tr.resx
src/HASS.Agent/HASS.Agent/HomeAssistant/Sensors/GeneralSensors/SingleValue/AccentColorSensor.cs
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.Designer.cs
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.de.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.en.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.es.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.fr.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.nl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pt-br.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.ru.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.sl.resx
src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.tr.resx
src/HASS.Agent/HASS.Agent/Sensors/SensorsManager.cs
src/HASS.Agent/HASS.Agent/Settings/StoredSensors.cs

This PR adds feature requested by @kineticscreen via https://github.com/hass-agent/HASS.Agent/issues/290.
The new sensor provides main system accent color as a value and all of them as additional attributes.
Example in the mentioned PR.

Feature: accent color sensor

---

src/HASS.Agent/HASS.Agent/Forms/QuickActions/QuickActions.cs

This PR fixes issue reported by @MathisP75 via https://github.com/hass-agent/HASS.Agent/issues/258 where the quick actions window would retain the same size, even on systems with scale larger than 100%.

Fix: quick actions window scaling

---

src/HASS.Agent/HASS.Agent/Controls/Onboarding/Onboarding-6-HotKey.cs

This PR (hopefully once and for all) fixes issue reported by @FatalMerlin via https://github.com/hass-agent/HASS.Agent/issues/219 where the Alt+Control+Q hotkey would mess up with german keyboard layouts.
The default hotkey is changed to Shift+Control+Q as suggested in the issue.
More details can be found within the issue report itself.

Fix: change default hotkey to Shift+Control+Q

---

src/HASS.Agent.Installer/InstallerScript.iss

This PR fixes issue reported by @KrX3D via https://github.com/hass-agent/HASS.Agent/issues/151 where the InnoSetup launch parameters would not be passed on to the satellite service installer.

Fix: installer parameters not being passed on to the satellite installer

---

src/HASS.Agent/HASS.Agent.Satellite.Service/Functions/HelperFunctions.cs
src/HASS.Agent/HASS.Agent.Satellite.Service/Worker.cs

This PR fixes issue reported via https://github.com/hass-agent/HASS.Agent/issues/311.
There was missing AudioManager initialisation in the worker code that causes AudioSensor not to function properly.

Fix: added missing AudioManager initialization from satellite service

---

.github/workflows/build.yml
src/HASS.Agent/HASS.Agent/HomeAssistant/Commands/InternalCommands/RadioCommand.cs

This PR fixes issue reported by @barrelltitor via https://github.com/hass-agent/HASS.Agent/issues/331 where configuring bluetooth dongle with RadioCommand and then removing the dongle would cause HASS.Agent to crash/be unable to start.

Fix: bluetooth dongle radio absence causing application crash

---

src/HASS.Agent/HASS.Agent/Controls/Configuration/ConfigTrayIcon.cs
src/HASS.Agent/HASS.Agent/Functions/HelperFunctions.cs

This PR fixes issue reported via https://github.com/hass-agent/HASS.Agent/issues/343 where the default webview screen configuration would not be initialised before showing the webview. This resulted in application crash.

Fix: crash when trayicon web view screen was not manually configured
