hass-agent/HASS.Agent

- src/HASS.Agent.Staging/HASS.Agent/Forms/Main.cs
This PR:
- fixed the Local API being enabled causing initial load process to fail
> Fix: Local Api being enbaled handing load process

- README.md
- src/HASS.Agent.Staging/HASS.Agent/Forms/Commands/CommandsMod.cs
- src/HASS.Agent.Staging/HASS.Agent/Forms/Main.cs
- src/HASS.Agent.Staging/HASS.Agent/Forms/Sensors/SensorsMod.cs
- src/HASS.Agent.Staging/HASS.Agent/HASS.Agent.csproj
- src/HASS.Agent.Staging/HASS.Agent/HomeAssistant/Commands/CustomCommands/SwitchDesktopCommand.cs
- src/HASS.Agent.Staging/HASS.Agent/HomeAssistant/Sensors/GeneralSensors/SingleValue/ActiveDesktopSensor.cs
- src/HASS.Agent.Staging/HASS.Agent/Managers/VirtualDesktopManager.cs
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.Designer.cs
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.de.resx
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.en.resx
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.es.resx
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.fr.resx
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.nl.resx
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.pl.resx
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.pt-br.resx
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.resx
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.ru.resx
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.sl.resx
- src/HASS.Agent.Staging/HASS.Agent/Resources/Localization/Languages.tr.resx
This release includes fixes for issues reported via https://github.com/amadeo-alex/HASS.Agent/issues/10
> Release: 2023.11.1-ubeta

- src/HASS.Agent/HASS.Agent/Managers/UpdateManager.cs
- src/HASS.Agent/HASS.Agent/Variables.cs
This PR:
- changes the certificate hash to the one of certificate that will be used to sign the installer
- adds cutoff date for releases during new version check
> Feature: updater changes

- README.md
- src/HASS.Agent.Installer/InstallerScript.iss
- src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
- src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
- src/HASS.Agent/HASS.Agent/HASS.Agent.csproj
- src/HASS.Agent/HASS.Agent/Managers/UpdateManager.cs
This release:
- fixes minor bug with the project files resulting in git hash being added to product version
- removes unused variable which caused UpdateManager to throw exception with malformed version created by above bug
> Release: 2.0.1

- src/HASS.Agent.Installer/InstallerScript.iss
- src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
- src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
- src/HASS.Agent/HASS.Agent/HASS.Agent.csproj
This PR changes internal version of projects and installer to 2.1.0-beta1
> Development: 2.1.0-beta1 version change

- src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/GeneralSensors/SingleValue/MicrophoneProcessSensor.cs
This PR makes the microphone process sensors attributes to be cleared when no process is using the microphone.
> Fix: microphone process sensor attributes clearing

- src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/GeneralSensors/SingleValue/ActiveWindowSensor.cs
This PR adds "ProcessName" attribute to the ActiveWindowSensor.
Requested via https://github.com/hass-agent/HASS.Agent/issues/73
> Feature: ActiveWindowSensor process name

- src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/WmiQuerySensor.cs
This PR adds additional checks for WMI sensor where one of the property values can be null.
> Fix: wmi sensor property value being null

- src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/GeneralSensors/SingleValue/ScreenshotSensor.cs
This PR fixes screenshot sensor capturing only part of the screen when "non 100%" scaling.
Thanks for @ElDingo424 for reporting - https://github.com/hass-agent/HASS.Agent/issues/81
> Fix: screenshot sensor monitor scaling

- src/HASS.Agent/HASS.Agent.Shared/Enums/HassAction.cs
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.Designer.cs
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.de.resx
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.en.resx
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.es.resx
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.fr.resx
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.nl.resx
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.pl.resx
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.pt-br.resx
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.resx
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.ru.resx
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.sl.resx
- src/HASS.Agent/HASS.Agent.Shared/Resources/Localization/Languages.tr.resx
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.Designer.cs
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.de.resx
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.en.resx
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.es.resx
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.fr.resx
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.nl.resx
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pl.resx
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.pt-br.resx
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.resx
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.ru.resx
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.sl.resx
- src/HASS.Agent/HASS.Agent/Resources/Localization/Languages.tr.resx
This PR adds feature requested via https://github.com/hass-agent/HASS.Agent/issues/117 that allows to configure quick action to trigger an automation configured in Home Assistant.
> Feature: quick action automation trigger

- src/HASS.Agent.Installer/InstallerScript-Service.iss
- src/HASS.Agent.Installer/InstallerScript.iss
- src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
- src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
- src/HASS.Agent/HASS.Agent/HASS.Agent.csproj
Bumped version and minor installer text change to note that migrate option should be used only once.
> Release: 2.1.0-beta3

- src/HASS.Agent/HASS.Agent/Forms/WebView.cs
- src/HASS.Agent/HASS.Agent/Functions/HelperFunctions.cs
This PR fixes issue reported via https://github.com/hass-agent/HASS.Agent/issues/137 where the webview would always appear in the same predefined spot in all taskbar configurations (top, left, right, bottom).
> Fix: webview not respecting taskbar location

- src/HASS.Agent.Installer/BeforeInstallNotice.rtf
- src/HASS.Agent.Installer/InstallerScript-Service.iss
- src/HASS.Agent.Installer/InstallerScript.iss
- src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
- src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
- src/HASS.Agent/HASS.Agent/HASS.Agent.csproj
This PR removes all references to beta4 and adjusts some of the wording during installation.
> Release: 2.1.0

- src/HASS.Agent/HASS.Agent/Managers/StorageManager.cs
This PR adds logic required to properly show notification images passed with relative URL - "/media/pics/image.png".
Thanks to @iankaufmann for reporting! https://github.com/hass-agent/HASS.Agent/issues/178
> Fix: added logic to handle HA relative media URLs

- src/HASS.Agent/HASS.Agent/Controls/Configuration/ConfigMediaPlayer.cs
- src/HASS.Agent/HASS.Agent/Controls/Configuration/ConfigNotifications.cs
- src/HASS.Agent/HASS.Agent/Forms/Commands/CommandConfig/CommandMqttTopic.cs
- src/HASS.Agent/HASS.Agent/Forms/Commands/CommandsConfig.cs
- src/HASS.Agent/HASS.Agent/Forms/Commands/CommandsMod.cs
> Fix: update dead documentation links

- src/HASS.Agent.Installer/InstallerScript-Service.iss
- src/HASS.Agent.Installer/InstallerScript.iss
- src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
- src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
- src/HASS.Agent/HASS.Agent/HASS.Agent.csproj
- Media player now respects the user-provided value in mute service call (thanks to @TarheelGrad1998 for reporting) https://github.com/hass-agent/HASS.Agent/pull/185
- Notification image not being shown when relative "/media/pics/image.png" was used instead of full URL (thanks to @iankaufmann for reporting) https://github.com/hass-agent/HASS.Agent/pull/186
- UI not displaying properly on high-DPI devices with scaling other than 100% (thanks to @IsaacInsoll for reporting) https://github.com/hass-agent/HASS.Agent/pull/187
- Some of the documentations links were pointing to non-existing pages (thanks to @SVNKoch for the PR!) https://github.com/hass-agent/HASS.Agent/pull/159
- Pressing ESC while having Alt+Tab pressed caused HASS.Agent windows to close (thanks to @SVNKoch for reporting and …
> Release: 2.1.1-beta2

- .github/workflows/build.yml
- src/HASS.Agent.Installer/InstallerScript-Service.iss
- src/HASS.Agent.Installer/InstallerScript.iss
- src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
- src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
- src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Commands/InternalCommands/SetVolumeCommand.cs
- src/HASS.Agent/HASS.Agent.Shared/HomeAssistant/Sensors/WmiQuerySensor.cs
- src/HASS.Agent/HASS.Agent.Shared/Managers/Audio/AudioManager.cs
- src/HASS.Agent/HASS.Agent.Shared/Managers/PowershellManager.cs
- src/HASS.Agent/HASS.Agent/Controls/Configuration/ConfigMediaPlayer.cs
- src/HASS.Agent/HASS.Agent/Controls/Configuration/ConfigNotifications.cs
- src/HASS.Agent/HASS.Agent/Forms/Commands/CommandConfig/CommandMqttTopic.cs
- src/HASS.Agent/HASS.Agent/Forms/Commands/CommandsConfig.cs
- src/HASS.Agent/HASS.Agent/Forms/Commands/CommandsMod.cs
- src/HASS.Agent/HASS.Agent/Forms/Main.cs
- src/HASS.Agent/HASS.Agent/HASS.Agent.csproj
- src/HASS.Agent/HASS.Agent/MQTT/MqttManager.cs
- src/HASS.Agent/HASS.Agent/Managers/StorageManager.cs
- src/HASS.Agent/HASS.Agent/Media/MediaManager.cs
- src/HASS.Agent/HASS.Agent/Program.cs
- src/HASS.Agent/HASS.Agent/app.manifest
This PR merges changes from 2.1.1-beta3, updates various GH action versions and bumps build target framework version to net6.0-windows10.0.22621.0.
> Feature: merge with 2.1.1-beta3, GithubActions update and target version bump to net6.0-windows10.0.22621.0

- src/HASS.Agent.Installer/InstallerScript-Service.iss
- src/HASS.Agent.Installer/InstallerScript.iss
- src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
- src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
- src/HASS.Agent/HASS.Agent/HASS.Agent.csproj
development-2.1.1-beta3:
- MQTT autodiscovery messages were not republished after connection was lost and recovered (thanks to @whc2001 for reporting) https://github.com/hass-agent/HASS.Agent/pull/230
- URI attached to a notification button wouldn't open properly https://github.com/hass-agent/HASS.Agent/pull/229
- Satellite Service exe path is now properly enclosed in double quotes according to good security practices (thanks to @yakidd for reporting) https://github.com/hass-agent/HASS.Agent/pull/221
- Media playback via Music Assistant wasn't working correctly (thanks to @felipecrs and @whc2001 for reporting, providing a lot of information and testing) https://github.com/hass-agent/HASS.Agent/pull/220
- PowershellCommand argument handling where passing arguments containing spaces/quotes …
> Release: 2.1.1

- src/HASS.Agent/HASS.Agent.Shared/Managers/Audio/AudioManager.cs
This PR fixes issue reported by @floriangagnard via https://github.com/hass-agent/HASS.Agent/issues/257 where unplugging the input/output device after HASS.Agent was started would result in repeated error logs.
> Fix: audio sensor looping error when no default input/output device is present

- src/HASS.Agent.Installer/InstallerScript-Service-x86.iss
- src/HASS.Agent.Installer/InstallerScript-Service.iss
- src/HASS.Agent.Installer/InstallerScript-x86.iss
- src/HASS.Agent.Installer/InstallerScript.iss
- src/HASS.Agent/HASS.Agent.Satellite.Service/HASS.Agent.Satellite.Service.csproj
- src/HASS.Agent/HASS.Agent.Shared/HASS.Agent.Shared.csproj
- src/HASS.Agent/HASS.Agent/HASS.Agent.csproj
Quick fix release (this time with changed versions...)
> Release: 2.2.0-beta2
